version: '3.8'
services:
  postgres:
    image: postgres:17-alpine
    container_name: exprezzzo-house-postgres-1
    environment:
      POSTGRES_DB: exprezzzo
      POSTGRES_USER: exprezzzo
      POSTGRES_PASSWORD: Exp3zzz0_2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: exprezzzo-house-redis-1
    ports:
      - "6379:6379"
    command: redis-server --requirepass Exp3zzz0_Redis

  ollama:
    image: ollama/ollama:latest
    container_name: exprezzzo-house-ollama-1
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data:
