headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/home/jaydev/exprezzzo-house/mobile-house"
publishOrigin = "config"
commandOrigin = "ui"
base = "/home/jaydev/exprezzzo-house/mobile-house"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]