services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: exprezzzo-postgres
    environment:
      POSTGRES_USER: exprezzzo
      POSTGRES_PASSWORD: VegasAlwaysWins2025
      POSTGRES_DB: sovereign_brain
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exprezzzo"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: exprezzzo-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: exprezzzo-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama
    environment:
      OLLAMA_HOST: "0.0.0.0"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: exprezzzo-api
    ports:
      - "3001:3001"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      DATABASE_URL: "postgresql://exprezzzo:VegasAlwaysWins2025@postgres:5432/sovereign_brain"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - postgres
      - redis
